version: '3.8'

services:
  flask_backend:
    build: ./ShipRouting
    ports:
      - "5000:5000"
    networks:
      - app-network

  flutter_frontend:
    build: ./route_application
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
